spring.application.name=auth-service
server.port=8081


# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/AuthService
spring.datasource.username=postgres
spring.datasource.password=434680
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT Configuration
jwt.secret=mySuperSecureSecretKeyThatIsAtLeast32Characters12345
jwt.access-expiration=900000
jwt.refresh-expiration=604800000


spring.security.oauth2.client.registration.google.client-id =1061371119171-oa1cfiid073p1vectk6t1vs6m3cm8v3b.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret =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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

resend.api-key:re_bQk9PJtY_fB7CpPjKNiGrNuBbDZ6ZnDVh
resend.from-email: "PrevYearPaper App <noreply@pdeep.store>"