server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server: # 'server' is required for WebMVC Gateway
        webmvc:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications/**
            - id: university-service
              uri: lb://UNIVERSITY-SERVICE
              predicates:
                - Path=/api/v1/global-admin/**,/api/v1/university-rep/**, /api/v1/department-rep/**, /api/v1/program-rep/**,/api/v1/session-rep/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/