services:
  notification-service:
    image: ${DOCKER_USERNAME}/prevpaper-notification-service:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SERVER_PORT: "8085"
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP}
      SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: ${KAFKA_SASL_JAAS_CONFIG}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_EMAIL_FROM: ${RESEND_FROM_EMAIL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      TWILIO_VERIFY_SERVICE_SID: ${TWILIO_VERIFY_SERVICE_SID}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: ${ZIPKIN_ENDPOINT}
      EUREKA_CLIENT_ENABLED: "false"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
