server.port=8085

spring.application.name=notificationService
spring.datasource.url=jdbc:postgresql://localhost:5432/notificationService
spring.datasource.username=postgres
spring.datasource.password=434680

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


resend.api.key=re_bQk9PJtY_fB7CpPjKNiGrNuBbDZ6ZnDVh
resend.email.from=noreply@pdeep.store


#twilio.account-sid=ACacad4a981f0d369bb88592fa26cd5aaf
#twilio.auth-token=c4be76aa8b14b6753302c844595e6b22
#twilio.phone-number=+15005550006
#
#
#twilio.verify_service_sid=VA1cd5db3587ec53bd630e7d8973f459dd


# Make sure there are NO spaces around the '=' sign
# twilio.properties
# Ensure there are no leading or trailing spaces!

twilio.account_sid=ACacad4a981f0d369bb88592fa26cd5aaf
twilio.auth_token=c4be76aa8b14b6753302c844595e6b22
twilio.phone_number=+15005550006
twilio.verify_service_sid=VA1cd5db3587ec53bd630e7d8973f459dd